import { Category } from './category.model';

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  rating: number;
  image: string;
  images: string[];
  link: string;
  categoryId: number;
  reviewCount: number;
  inStock: boolean;
  likes: number;
  isFavorite: boolean;
}

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Smartphones', icon: '📱' },
  { id: 2, name: 'Laptops',     icon: '💻' },
  { id: 3, name: 'Headphones',  icon: '🎧' },
  { id: 4, name: 'Tablets',     icon: '📲' },
];

export const PRODUCTS: Product[] = [
  // ── Smartphones (categoryId: 1) ──────────────────────────────────────
  {
    id: 1,
    name: 'Apple iPhone 15 Pro Max 256GB',
    description: 'Titanium design, A17 Pro chip, 48 MP ProRAW camera system and Action Button. The most powerful iPhone ever made.',
    price: 849990,
    rating: 4.9,
    image: 'images/iphone15.jpg',
    images: ['images/iphone15.jpg', 'images/iphone15_2.jpg', 'images/iphone15_3.jpg', 'images/iphone15_1.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-iphone-15-pro-max-256gb-natural-titanium-113138363/',
    categoryId: 1,
    reviewCount: 2847,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24 Ultra 256GB',
    description: 'Galaxy AI, integrated S Pen, 200 MP camera and titanium frame. The ultimate Android flagship.',
    price: 637000,
    rating: 4.8,
    image: 'images/samsung.jpg',
    images: ['images/samsung.jpg', 'images/samsung1.jpg', 'images/samsung2.jpg', 'images/samsung3.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-s24-ultra-5g-12-gb-256-gb-seryi-116043556/',
    categoryId: 1,
    reviewCount: 1523,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 3,
    name: 'Xiaomi Redmi Note 13 Pro 8/256GB',
    description: '200 MP main camera, 120 Hz AMOLED display and 67 W turbo charging at an unbeatable price.',
    price: 150721,
    rating: 4.6,
    image: 'images/redmi.jpg',
    images: ['images/redmi.jpg'],
    link: 'https://kaspi.kz/shop/p/xiaomi-redmi-note-13-pro-5g-8-gb-256-gb-chernyi-122771656/',
    categoryId: 1,
    reviewCount: 2134,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 4,
    name: 'Samsung Galaxy A55 5G 8/256GB',
    description: 'Bright 6.6-inch AMOLED display, 50 MP triple camera and IP67 water resistance. Style meets performance.',
    price: 199990,
    rating: 4.5,
    image: 'images/samsung2.jpg',
    images: ['images/samsung2.jpg', 'images/samsung3.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-a55-5g-8-gb-256-gb-sinii-120819008/',
    categoryId: 1,
    reviewCount: 876,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 5,
    name: 'Apple iPhone 14 128GB',
    description: 'A15 Bionic chip, 12 MP Dual camera and Emergency SOS via satellite. Powerful and reliable everyday phone.',
    price: 459990,
    rating: 4.7,
    image: 'images/iphone15_1.jpg',
    images: ['images/iphone15_1.jpg', 'images/iphone15_2.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-iphone-14-128gb-midnight-108048602/',
    categoryId: 1,
    reviewCount: 3112,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },

  // ── Laptops (categoryId: 2) ──────────────────────────────────────────
  {
    id: 6,
    name: 'Apple MacBook Air 15 M3 8/256GB',
    description: 'M3 chip, 15.3-inch Liquid Retina display, up to 18 h battery — the thinnest 15-inch laptop on the market.',
    price: 611933,
    rating: 4.9,
    image: 'images/macbook.jpg',
    images: ['images/macbook.jpg', 'images/macbook1.jpg', 'images/macbook2.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-macbook-air-15-2024-15-3-8-gb-ssd-256-gb-macos-mryu3-118170044/',
    categoryId: 2,
    reviewCount: 892,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 7,
    name: 'Apple MacBook Pro 14 M3 Pro 18/512GB',
    description: 'M3 Pro chip, ProMotion XDR display, Space Black finish. Built for professionals who demand maximum performance.',
    price: 999990,
    rating: 4.9,
    image: 'images/macbook1.jpg',
    images: ['images/macbook1.jpg', 'images/macbook2.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-macbook-pro-14-2023-14-2-18-gb-ssd-512-gb-macos-mrx33-118078490/',
    categoryId: 2,
    reviewCount: 412,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 8,
    name: 'Apple MacBook Air 13 M2 8/256GB',
    description: 'M2 chip in a fanless redesigned body with MagSafe charging. Silent, fast, and incredibly thin.',
    price: 479990,
    rating: 4.8,
    image: 'images/macbook2.jpg',
    images: ['images/macbook2.jpg', 'images/macbook.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2022-13-6-8-gb-ssd-256-gb-macos-mlxw3-103483622/',
    categoryId: 2,
    reviewCount: 1534,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 9,
    name: 'Samsung Galaxy Book4 Pro 16 i7 16/512GB',
    description: 'Intel Core Ultra 7, 3K AMOLED display and up to 25 h battery. A Windows powerhouse for creators.',
    price: 589990,
    rating: 4.7,
    image: 'images/samsung1.jpg',
    images: ['images/samsung1.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-book4-pro-360-16-serebristo-seryi-124095706/',
    categoryId: 2,
    reviewCount: 234,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 10,
    name: 'Xiaomi Mi Notebook Pro 14 i5 16/512GB',
    description: '12th-gen Intel Core i5, 2.8K IPS display and ultra-thin metal chassis. Premium value for everyday pros.',
    price: 299990,
    rating: 4.5,
    image: 'images/lg1.jpg',
    images: ['images/lg1.jpg'],
    link: 'https://kaspi.kz/shop/p/xiaomi-mi-notebook-pro-14-2022-14-0-16-gb-ssd-512-gb-windows-jyu4456cn-120266070/',
    categoryId: 2,
    reviewCount: 567,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },

  // ── Headphones (categoryId: 3) ───────────────────────────────────────
  {
    id: 11,
    name: 'Apple AirPods Pro 2nd Gen',
    description: '2x Active Noise Cancellation, Adaptive Audio and Personalized Spatial Audio with dynamic head tracking.',
    price: 103488,
    rating: 4.8,
    image: 'images/airpods.jpg',
    images: ['images/airpods.jpg', 'images/airpods1.jpg', 'images/airpods2.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-generation-with-wireless-magsafe-charging-case-belyi-113677582/',
    categoryId: 3,
    reviewCount: 4567,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 12,
    name: 'Apple AirPods 3rd Gen',
    description: 'Spatial Audio, Adaptive EQ, sweat- and water-resistant design with MagSafe Charging Case.',
    price: 69990,
    rating: 4.7,
    image: 'images/airpods1.jpg',
    images: ['images/airpods1.jpg', 'images/airpods2.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-3rd-generation-with-magsafe-charging-case-belyi-102285596/',
    categoryId: 3,
    reviewCount: 2890,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 13,
    name: 'Apple AirPods Max Silver',
    description: 'Over-ear headphones with industry-leading ANC, Transparency mode and High-Fidelity Audio.',
    price: 249990,
    rating: 4.8,
    image: 'images/airpods2.jpg',
    images: ['images/airpods2.jpg', 'images/airpods.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-max-serebristyi-89397176/',
    categoryId: 3,
    reviewCount: 987,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 14,
    name: 'Samsung Galaxy Buds2 Pro',
    description: '360-degree Audio, 2.7 mm two-way speaker, 29 h total battery and intelligent ANC.',
    price: 74990,
    rating: 4.6,
    image: 'images/samsung3.jpg',
    images: ['images/samsung3.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-buds2-pro-graphite-107434272/',
    categoryId: 3,
    reviewCount: 1765,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 15,
    name: 'Dyson Zone Noise-Cancelling Headphones',
    description: "World's first wearable air purifier combined with high-fidelity headphones — pure air and pure sound.",
    price: 289990,
    rating: 4.4,
    image: 'images/dyson.jpg',
    images: ['images/dyson.jpg', 'images/dyson1.jpg'],
    link: 'https://kaspi.kz/shop/p/dyson-zone-absolute-prussian-blue-bright-copper-104793786/',
    categoryId: 3,
    reviewCount: 312,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },

  // ── Tablets (categoryId: 4) ──────────────────────────────────────────
  {
    id: 16,
    name: 'iPad Pro 12.9 M2 256GB Wi-Fi',
    description: 'M2 chip, Liquid Retina XDR display and Apple Pencil hover. The ultimate iPad for creative professionals.',
    price: 499900,
    rating: 4.9,
    image: 'images/ipad.jpg',
    images: ['images/ipad.jpg', 'images/ipad1.jpg', 'images/ipad2.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-ipad-pro-11-2022-wi-fi-11-djuim-8-gb-256-gb-seryi-107276752/',
    categoryId: 4,
    reviewCount: 1234,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 17,
    name: 'iPad Air 5th Gen 10.9 M1 64GB',
    description: 'M1 chip, 10.9-inch Liquid Retina display, USB-C and Apple Pencil 2nd gen compatibility.',
    price: 349990,
    rating: 4.8,
    image: 'images/ipad1.jpg',
    images: ['images/ipad1.jpg', 'images/ipad2.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-ipad-air-10-9-2022-wi-fi-64-gb-goluboi-101706186/',
    categoryId: 4,
    reviewCount: 2156,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 18,
    name: 'iPad 10th Gen 10.9 64GB Wi-Fi Blue',
    description: 'All-screen design, A14 Bionic chip and USB-C connectivity. Perfect for everyday tasks and entertainment.',
    price: 229990,
    rating: 4.6,
    image: 'images/ipad2.jpg',
    images: ['images/ipad2.jpg', 'images/ipad.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-ipad-10th-generation-10-9-2022-wi-fi-64-gb-sinii-107543584/',
    categoryId: 4,
    reviewCount: 3001,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 19,
    name: 'Samsung Galaxy Tab S9+ 12/256GB',
    description: 'Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, IP68 rating and included S Pen.',
    price: 419990,
    rating: 4.8,
    image: 'images/samsung1.jpg',
    images: ['images/samsung1.jpg', 'images/samsung2.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-tab-s9-5g-12-gb-256-gb-grafitovyi-116099016/',
    categoryId: 4,
    reviewCount: 678,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
  {
    id: 20,
    name: 'Xiaomi Pad 6 Pro 8/256GB',
    description: 'Snapdragon 8+ Gen 1, 144 Hz 2.8K display and 67 W fast charging. Flagship performance for less.',
    price: 199990,
    rating: 4.6,
    image: 'images/lg2.jpg',
    images: ['images/lg2.jpg'],
    link: 'https://kaspi.kz/shop/p/xiaomi-pad-6-pro-wi-fi-8-gb-256-gb-chernyi-115571252/',
    categoryId: 4,
    reviewCount: 890,
    inStock: true,
    likes: 0,
    isFavorite: false,
  },
];
